#+TITLE: 8004 Homework 8
#+AUTHOR: Nooreen Dabbish
#+Email: nerd@temple.edu
#+LATEX_HEADER: \usepackage{methodshw, amsmath}
#+OPTIONS: toc:nil

# Code to input variables, libraries, and commonly used functions:
#+NAME: common
#+BEGIN_SRC R :session *HW8* :exports none :tangle yes
       library(MASS); library(xtable);library(nlme)
         lvector <- function(x, dig = 2, dsply=rep("f",ncol(x)+1)) {
          x <- xtable(x, align=rep("",ncol(x)+1),display=dsply,digits=dig) # We repeat empty string 6 times
          print(x, floating=FALSE, tabular.environment="pmatrix", 
            hline.after=NULL, include.rownames=FALSE, include.colnames=FALSE)
          }
#+END_SRC

#+RESULTS: common

* This is Problem 3 of Faraway (2006), Chapter 9

The ~ratdrink~ data consist of five weekly measurements of body
weight for 27 rats. The first 10 rats are on a control treatment
while seven rats have thyroxine added to their drinking water. Ten
rats have thiouracil added to their water. Build a model for the rat
weights that shows the effect of the treatment.

#+BEGIN_SRC R :session *HW8* :exports code :tangle yes 
  library(faraway)
  data(ratdrink)
#+END_SRC

** Model the weights of the rate, incorporating the treatment effects and random effect. Use ~R~ to fit the model.

We write y_{ijk} to represent the kth rat in the jth treatment group
on the ith week, where (i=1,2,3,4), (j=1,2,3), and (k= 1-10 for
control, k = 1-7 thyroxine, and k = 1-10 for thiouracil). \mu
represents the overall mean weight, \alpha_i represents the fixed
effect contribution of the ith week, \beta_j repsents the fixed
effect contribution of the jth treatment, and \delta_{ij} is the
interaction of weeks and treatment. The random effect u_{jk}
incorporates the repeated measures of the same rat.

$$y_{ijk} = \mu + \alpha_i + \beta_j + \delta_{ij} + u_{jk} + \epsilon_{ijk}$$


#+BEGIN_SRC R :session *HW8* :exports none :tangle yes 
  help(ratdrink)
  library(lattice)
  
  ratdrink$thecolor = "black"
  ratdrink$thecolor[ratdrink$treat == "thyroxine"] = "red"
  ratdrink$thecolor[ratdrink$treat == "thiouracil"] = "blue"
  attach(ratdrink)
  pdf("ratweights.pdf",width=7,height=5)
  plot(weeks, wt, col = thecolor, main="Rat growth weights affected by additives")
  legend("topleft", c("Control", "Thyroxine", "Thiouracil"), col=c("black","red","blue"), pch=1)
  dev.off()
  
#+END_SRC

To fit the model in R we write:

#+BEGIN_SRC R :session *HW8* :exports both :tangle yes 
  library(lme4)
  rat.lme <- lmer(wt ~ weeks+ treat+ weeks*treat+ (1|subject))
  summary(rat.lme)
#+END_SRC


** What is the implication of the random effect on the correlations between weights of the same rat? Is that implication reasonable? It would be nice to support your argument with data evidence.


* The article “Variability of Sliver Weights at Different Carding Stages and a Suggested Sampling Plan for Jute Processing” 
by A. Lahiri (Journal of the Textile Institute, 1990) concerns the 
partitioning
of variability in “sliver weight.” (A sliver is a continuous strand
of loose, untwisted wool, cotton,
etc., produced along the way to making yarn.) For a particular mill, 
3 (of many) machines were
studied, using 5 (10 mm) pieces of sliver cut from each of 5 rolls produced on the machines. The
weights of the (75) pieces of sliver were determined and a standard hierarchical (balanced data)
ANOVA table was produced as below. (The units of weight were not given in the original article.)

| Source   |   SS | df |
|----------+------+----|
| Machines | 1966 |  2 |
| Rolls    |  644 | 12 |
| Pieces   |  280 | 60 |
|----------+------+----|
| Total    | 2890 | 74 |


The model is $$y_{ijk} = \mu + \alpha_i +u_{ij} + \epsilon_{ijk}$$

for the kth piece of the jth roll on the ith machine, where
$\alpha_i\overset{iid}{\sim} N(0,\sigma^2_\alpha)$,
$\u_{ij}\overset{iid}{\sim} N(0,\sigma^2_u)$, and $\epsilon_i\overset{iid}{\sim} N(0,\sigma^2_\epsilon)$,  


* Appendix: Tangled R Code
:PROPERTIES:
:UNNUMBERED: t
:END:

\lstinputlisting{DabbishHW8.R} 

* Appendix: Initial evaluation of ratdrink dataset

[[./ratweights.pdf]]

Plotting the ratdrink data suggested that rats that drank Thyroxine
tended to have increased body weight after 5 weeks in comparison to rats
drinking Thiouracil and Control. The rats that drank Thiouracil
tended to have lowerbody weight than the Control and Thyroxine groups.




