#+TITLE: 8004 Homework 4
#+AUTHOR: Nooreen Dabbish
#+Email: nerd@temple.edu
#+LATEX_HEADER: \usepackage{methodshw, amsmath}
#+OPTIONS: toc:nil

# Code to input variables, libraries, and commonly used functions:
#+NAME: common
#+BEGIN_SRC R :session *HW6* :exports none :tangle yes
       library(MASS); library(xtable)
         lvector <- function(x, dig = 2, dsply=rep("f",ncol(x)+1)) {
          x <- xtable(x, align=rep("",ncol(x)+1),display=dsply,digits=dig) # We repeat empty string 6 times
          print(x, floating=FALSE, tabular.environment="pmatrix", 
            hline.after=NULL, include.rownames=FALSE, include.colnames=FALSE)
          }
#+END_SRC

* A meat scientist is studying the effect of storage temperature on meat quality. 
The temperatures of interest are 34, 40, and 46 degrees Fahrenheit. Twelve coolers are available for the study. The three temperatures are randomly assigned to the twelve coolers using a balanced and completely randomized design. Two large cuts of fresh beef are stored in each cooler. After three days, each member of a team of experts independently assigns a quality score to each cut of beef. The experts are not told about the storage conditions of each cut. The scores assigned by the team to each cut of beef are averaged to produce an overall quality score for each cut.

** Write down a model for the overall quality score data. Define your notation thoroughly.

Let y_{ijk} = the overall quality score for the kth cut from the jth
cooler at the ith temperature, where k = 1,2, j = 1,2,3,4, and
i=1,2,3.

The three temperatures of interest are pre-determined, so we will
consider them fixed effects, the fixed effect of the ith temperature
is \beta_i. Whereas the effects of cooler at each temperature are
random, given by u_{ij} for the jth cooler at the ith temperature.
Also, we will add in an overall mean \mu which is also fixed,
giving the model: 

$$y_{ijk} = \mu + \beta_i + u_{ij} + \epsilon_{ijk}$$

We assume that 
 + $u_{ij}\overset{iid}\sim N(0,\sigma^2_u)$
 + the random error $\epsilon_{ijk}\overset{iid}\sim N(0,\sigma^2_\epsilon)$ 

* Let 
$$\begin{pmatrix} y_1 \\ y_2 \\ y_3 \end{pmatrix} \sim N 
\left(\begin{pmatrix} \mu_1 \\ \mu_1 \\ \mu_2 \end{pmatrix},
\begin{pmatrix} \sigma^2 & \sigma^2/2 & 0 \\ \sigma^2/2
& \sigma^2 & \sigma^2/2 \\ 0 & \sigma^2/2 & \sigma^2 \end{pmatrix}
\right)$$ 

Where \mu_1, \mu_2 and \sigma^2 are unknown parameters. 
Find the REML of \sigma^2. Please start with writing it as *Y=X\beta+\epsilon*, and then try to find *M* for calculating the REML.
 
We have *X* = $\begin{pmatrix} 1 & 0 \\ 1 & 0 \\ 0 & 1 \end{pmatrix}$, 
*\beta* = $\begin{pmatrix} \mu_1 \\ \mu_2 \end{pmatrix}$, and 
*\epsilon* $\sim N(0,\Sigma),\Sigma=\sigma^2
\begin{pmatrix} 1 & 1/2 & 0 \\ 1/2 & 1 & 1/2 \\ 0 & 1/2 & 1 \end{pmatrix}$.

\begin{align*}
\begin{pmatrix} y_1 \\ y_2 \\ y_3 \end{pmatrix} &= 
\begin{pmatrix} 1 & 0 \\ 1 & 0 \\ 0 & 1 \end{pmatrix} 
\begin{pmatrix} \mu_1 \\ \mu_2 \end{pmatrix} + \sigma^2 
\begin{pmatrix} 1 & 1/2 & 0 \\ 1/2 & 1 & 1/2 \\ 0 & 1/2 & 1 \end{pmatrix}
\end{align*}
